project:
  type: website
  output-dir: docs

website:
  title: "quarto_web"
  navbar:
    left:
      - href: index.qmd
        text: "Home"
      - hello.qmd
      - computations.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



